### PR TITLE
OR config param added to Compare

### PR DESCRIPTION
**Pull request by lamasgergo**
#101 improvement

### CODE REVIEW

**Comment by dereuromark** [comment]
Could we please have a small test case for this addition?

**Comment by burzum** [comment]
By looking at this, how about allowing to pass a callable as well and pass the query object on to it?

**Comment by ADmad** [comment]
@burzum We already have a Callback filter, so if you need to use a callback just use that.

**Comment by dereuromark** [comment]
@lamasgergo ping

**Comment by lamasgergo** [comment]
i§m on it, sorry i don't have enough time for write it yet. It needed a simple test, when we have checking for example on the "created" AND "modified" fields. 

> select * from articles where created >= '2016-11-14' OR modified >= '2016-11-14' 

I try to publish this simple test ASAP.

**Comment by dereuromark** [comment]
@lamasgergo Ok, thx!

**Comment by lamasgergo** [comment]
Thanks @dereuromark !

**Pull request closed without merging**
