### PR TITLE
Use query interface to allow for other data sources

### PR DESCRIPTION
**Pull request by Marlinc**
This would technically speaking break BC on the `query` method.

### CODE REVIEW

**Comment by dereuromark** [comment]
We should First Release a 2.4 and then we can merge and Release 3.0 here.

**Comment by dereuromark** [comment]
What is the plan of attack here?

**Comment by Marlinc** [comment]
I think its best to create a new release as this is a breaking change. I'm not sure though how many people actually override the query method.

Do you see any other things that I have to change before this is mergeable?

**Comment by jippi** [comment]
if we merge it we should just major bump, versions are cheap :)

**Comment by Marlinc** [comment]
Should I target another branch?

**Comment by dereuromark** [comment]
No, all good. We merge prior to the bump.

**Comment by Marlinc** [comment]
Okay, anything else I should do?

**Comment by ADmad** [comment]
I can merge this and bump version after other actionable open PRs are taken care of.

**Pull request merged**
