### PR TITLE
Finder map

### PR DESCRIPTION
**Pull request by dereuromark**
Almost always custom finders require certain keys to be present. And you cannot change that, especially not for plugin finders.

Make custom finders get the right fields via map functionality.

Refs https://github.com/dereuromark/cakephp-tools/pull/200 which needs this functionality.

### CODE REVIEW

**Comment by ADmad** [comment]
Would be a good idea to have a boolean option (maybe `onlyMapped`) to pass only the mapped fields as finder options?

**Comment by dereuromark** [comment]
I guess we dont need that since they all ignore overhead keys afaik. Didnt meet that use case that. :)

**Comment by ADmad** [comment]
BTW your use case can also be achieved using callback filter:

```php
$searchManager
    ->finder('callback', function ($query, $args) {
        $query->find('bits', ['bits' => $args['status']]);
    });

**Comment by dereuromark** [comment]
Anything can be achieved using that one ;)
The idea was to use the existing explicit finder one here IMO - as this is the tailored one for finder calls that should be preferred if possible.

**Comment by dereuromark** [comment]
@ADmad Actually, I was thinking, maybe we should invert from=>to into to=>from?
as they keys must be unique, and it could be more likely that you reuse the same incoming value twice, as the finder needs two keys (but same value) for example.

finder(custom, [foo=>x, bar=>x]) would then work with map of
```
'foo' => 'x',
'bar' => 'x'
```
and the posted key `x`.

I can quickly refactor and adjust docs before we release.

**Comment by ADmad** [comment]
Yup flipping the key value makes sense.

**Comment by ADmad** [comment]
Rebasing the feature branch onto master might make stickler happy.

**Comment by dereuromark** [comment]
Thx, that worked :)

**Pull request merged**
