### PR TITLE
allow prefixed/scoped/nested/dotnotated search params

### PR DESCRIPTION
**Pull request by htstudios**
However the UnitTest is broken as somehow the `searchManager()->add` calls seem to change nothing. Any hints?

### CODE REVIEW

**Comment by davidyell** [comment]
I don't understand the point of this feature. To me you could achieve the same using a `finder` type search, and then use a custom finder to contain any related data you wanted.

**Comment by htstudios** [comment]
As explained in IRC, you cannot. The point is that you do not have to write a ton of `finder` types and still be able to use multiple filters on the same single view (say /users/view/1).

**Comment by jippi** [comment]
there seem to be failing tests :)

**Comment by htstudios** [comment]
### Unit tests
I understood the source of the problem. 
Had to create a new test and fixture to avoid class name clashes and setup the manager.
Fixed it - but I am quite unhappy how I did it. Any ideas or is it fine?

**Comment by htstudios** [comment]
The failing test seems to be unrelated?!

**Comment by ADmad** [comment]
https://travis-ci.org/FriendsOfCake/search/jobs/151476411#L220

**Comment by ADmad** [comment]
Why did you make a new test case file instead of just adding new tests to existing `SearchBehaviorTest` ?

**Comment by htstudios** [comment]
@ADmad because in my process of working I had a lot of issues with the custom class ahead the Test File. I can probably merge stuff back now and simply use the comments fixture, ok?

**Comment by ADmad** [comment]
> I can probably merge stuff back now and simply use the comments fixture, ok?

Yes. You could also use a core fixture instead of making a new one in plugin. Core fixtures are available in [plugin tests](https://github.com/FriendsOfCake/search/blob/master/composer.json#L32).

**Comment by htstudios** [comment]
I would have kept the tests files separate as every test now needs to load the comments table, comments search setup, comments fixture. Anyway I merged that.

I did also use the core.Comments fixture - that's a lot better, thank you for the pointers!

Any more concerns, else I will try to squash the commit chaos.

**Comment by ADmad** [comment]
> every test now needs to load the comments table, 

You could have avoided that by loading table only in the required test method instead of `setUp()` but it doesn't really matter.

**Comment by htstudios** [comment]
Thanks for the quick @jippi merges and all the help, especially by @ADmad !

**Pull request merged**
