### PR TITLE
Remove deprecations for new major.

### PR DESCRIPTION
**Pull request by dereuromark**
To be merged after the other 3 PRs - and before tagging 3.0.1.

### CODE REVIEW

**Comment by dereuromark** [comment]
I suggest the following release notes for the tag:

```
### Improvements

Filters
- All filters should now return a boolean result on whether they modified the query.

Like
- `value` is now `fieldValue` config.
```

**Comment by dereuromark** [comment]
We can also wait with this cleanup for 4.x.

**Comment by josegonzalez** [comment]
Needs rebase.

**Comment by ADmad** [comment]
Changes in this PR are covered by #175

**Pull request closed without merging**
