### PR TITLE
Switch to Github Actions for CI.

### PR DESCRIPTION
**Pull request by ADmad**
TravisCI is ending free OSS support.

### CODE REVIEW

**Comment by dereuromark** [comment]
Nice work :)

**Comment by dereuromark** [comment]
Note: We should also switch the badge
https://github.com/spryker/decimal-object/pull/12 works nicely and links to the branch result only (no side effect of other branches for the display of master).

**Comment by ADmad** [comment]
The badge URL I have used is for master only.

**Comment by dereuromark** [comment]
Right. It looked different than the CI one.

PS: Do we want composer caching enabled?
https://github.com/actions/cache/blob/main/examples.md#php---composer

**Comment by dereuromark** [comment]
This worked for me (using composer.json file to hash): https://github.com/dereuromark/cakephp-ide-helper/pull/220

**Comment by ADmad** [comment]
I don't want to use GA cache until they add a way to be able to explicitly purge the cache.

This (and many other plugins) don't gets updates often enough so the lack of caching won't hurt much.

**Pull request merged**
