### PR TITLE
Cake 4.x merge to master

### PR DESCRIPTION
**Pull request by dereuromark**
Once
- https://github.com/FriendsOfCake/search/issues/272

has been addressed, we can already merge to master here IMO.

### CODE REVIEW

**Comment by ADmad** [comment]
With the changes we have done recently I would prefer 1 more beta before we go to stable.

**Comment by dereuromark** [comment]
Can we make it an RC?

**Comment by ADmad** [comment]
Okay, guess RC works too

**Comment by dereuromark** [comment]
I created a cake3 branch. We can merge to master now.

**Comment by dereuromark** [comment]
We migth want to keep the branch for a while, some projects might already use it (as do I).

**Comment by ADmad** [comment]
Shouldn't have merged this until we were ready to release 6.0.0.

**Comment by dereuromark** [comment]
Yes, master is fine for 6.0 dev now for weeks.

**Pull request merged**
