### PR TITLE
Added a basic contents table links

### PR DESCRIPTION
**Pull request by davidyell**
The readme is kinda big, so this pull request aims to mitigate that by adding a contents 'table' of links, to get to specific parts quicker.

### CODE REVIEW

**Comment by dereuromark** [comment]
:-1: 
I actually just proposed a few days ago to keep readme lean and move the docs mainly to a subdir /docs as recommended in general.
Then this becomes not necessary anymore, or could be part of the /docs README one.

**Comment by davidyell** [comment]
I don't see why we can't merge this then in the meantime. As when the pull request for the next update comes through, we can overwrite this change.

**Comment by dereuromark** [comment]
Why not moving it already now?
Keeping this just invites the readme to get further exploded by too much content.

**Comment by davidyell** [comment]
Sure, go for it 👍

**Comment by dereuromark** [comment]
Do you want to move them to /docs/README.md ?
Keeping only the outline and basics in the readme then?

**Comment by davidyell** [comment]
I don't see any value in such a small change. If we are going to use a `/docs` folder, there should be documentation for each logical section of the plugin, with links in the main repo readme.

**Pull request merged**
