### PR TITLE
CakePHP 3.3: Allow scoped filters (/w scoped pagination)

### PR DESCRIPTION
**Pull request by htstudios**
Ref: http://book.cakephp.org/3.0/en/controllers/components/pagination.html#paginating-multiple-queries

### CODE REVIEW

**Comment by htstudios** [comment]
### Working Example

```sql
CREATE TABLE `languages` (
  `code` char(2) CHARACTER SET ascii NOT NULL DEFAULT '',
  `label` varchar(100) NOT NULL DEFAULT '',
  PRIMARY KEY (`code`),
  UNIQUE KEY `uniq_label` (`label`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

```php
        $this->addBehavior('Search.Search');
        $this->searchManager()
            ->add('Languages.code', 'Search.Like', [
                'before' => true,
                'after' => true,
                'mode' => 'or',
                'comparison' => 'LIKE',
                'wildcardAny' => '*',
                'wildcardOne' => '?',
                'field' => [$this->aliasField('code')]
            ])
            ->add('Languages.label', 'Search.Like', [
                'before' => true,
                'after' => true,
                'mode' => 'or',
                'comparison' => 'LIKE',
                'wildcardAny' => '*',
                'wildcardOne' => '?',
                'field' => [$this->aliasField('label')]
            ]);
    }
```

```php
        $this->loadComponent('Search.Prg', [
            // This is default config. You can modify "actions" as needed to make
            // the PRG component work only for specified methods.
            'actions' => ['index', 'lookup']
        ]);
        $this->loadComponent('Crud.Crud', [
            'actions' => [
                'index' => [
                    'className' => 'Crud.Index',
                    'relatedModels' => true
                ],
                'view' => [
                    'className' => 'Crud.View',
                    'relatedModels' => true
                ],
                'add' => [
                    'className' => 'Crud.Add',
                    'relatedModels' => true
                ],
                'edit' => [
                    'className' => 'Crud.Edit',
                    'relatedModels' => true
                ],
                'delete' => [
                    'className' => 'Crud.Delete',
                    'relatedModels' => false
                ],
                'lookup' => [
                    'className' => 'Crud.Lookup',
                    'relatedModels' => true
                ]
            ],
            'listeners' => [
                'Crud.RelatedModels',
                'Crud.Search',
                'Crud.Redirect',
            ]
        ]);
```
```php
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Html->link(__('New Language'), ['action' => 'add']) ?></li>
    </ul>
</nav>
<div class="languages index large-9 medium-8 columns content">
    <h3><?= __('Languages') ?></h3>
    <table cellpadding="0" cellspacing="0">
        <thead>
            <tr>
                <th>
                    <?= $this->Paginator->sort('code') ?>
                    <?= $this->Form->input('Languages.code', ['form' => 'LanguagesFilterForm', 'label' => false]) ?>
                </th>
                <th>
                    <?= $this->Paginator->sort('label') ?>
                    <?= $this->Form->input('Languages.label', ['form' => 'LanguagesFilterForm', 'label' => false]) ?>
                </th>
                <th class="actions">
                    <?= $this->Form->create(null, ['id' => 'LanguagesFilterForm']) ?>
                    <?= $this->Form->button('Filter', ['type' => 'submit', ['form' => 'LanguagesFilterForm']]) ?>
                    <?= $this->Html->link('Reset', ['action' => 'index']) ?>    
                    <?= $this->Form->end() ?>
                </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($languages as $language): ?>
            <tr>
                <td><?= h($language->code) ?></td>
                <td><?= h($language->label) ?></td>
                <td class="actions">
                    <?= $this->Html->link(__('View'), ['action' => 'view', $language->code]) ?>
                    <?= $this->Html->link(__('Edit'), ['action' => 'edit', $language->code]) ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <div class="paginator">
        <ul class="pagination">
            <?= $this->Paginator->prev('< ' . __('previous')) ?>
            <?= $this->Paginator->numbers() ?>
            <?= $this->Paginator->next(__('next') . ' >') ?>
        </ul>
        <p><?= $this->Paginator->counter() ?></p>
    </div>
</div>
``

**Comment by ADmad** [comment]
Tests needed.

**Comment by htstudios** [comment]
@ADmad I suggest:
1. First resolve this: https://github.com/cakephp/cakephp/issues/9210
2. Then also Search plugin's PRG seems to remove pagination parameters - should there be a simple merge of $this->request->query or is this a bug?
3. After 1. and 2. I will try to find time to supply unit tests.

**Comment by htstudios** [comment]
Closing in favour of https://github.com/FriendsOfCake/search/pull/113

**Pull request closed without merging**
