### PR TITLE
Make search manager use RepositoryInterface instance instead of Table.

### PR DESCRIPTION
**Pull request by ADmad**
Refs UseMuffin/Webservice#18

### CODE REVIEW

**Comment by ADmad** [comment]
More changes will most likely be needed to make Search plugin work with non table datasource.

**Comment by dereuromark** [comment]
Is this already good to go?

**Comment by ADmad** [comment]
@jippi @lorenzo Any objections to merging this?

**Comment by josegonzalez** [comment]
Note: behaviors cannot be used on non-Table objects since the typehint is `Table`, not `RepositoryInterface`. Changing would be a BC-break (I think?) and @lorenzo made it sound like he wants them to be a new type of thing [here](https://github.com/cakephp/elastic-search/issues/83#issuecomment-180597705).

**Pull request merged**
